server:
  port: 9001
spring:
  datasource:
      url: jdbc:mysql://rm-2zertll02ijpf958zno.mysql.rds.aliyuncs.com/hiauth?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: Wkyy_1111
      driver-class-name: com.mysql.jdbc.Driver